#include "config.h"
#include "../version.c"
#include <common/pseudorand.h>
#include <common/setup.h>
#include <assert.h>
#include <stdio.h>

/* AUTOGENERATED MOCKS START */
/* Generated stub for siphash_seed */
const struct siphash_seed *siphash_seed(void)
{ fprintf(stderr, "siphash_seed called!\n"); abort(); }
/* AUTOGENERATED MOCKS END */

int main(int argc, char *argv[])
{
	common_setup(argv[0]);

	assert(cmp_release_version("v22.11"));
	assert(cmp_release_version("v22.11.1"));
	assert(cmp_release_version("v22.11.1-6-gdf29990-modded") == false);
	assert(cmp_release_version("v26.06.8-blake2b.5"));
	assert(cmp_release_version("v26.06.8-blake2b.") == false);
	assert(cmp_release_version("v26.06.8-blake2b.5-rc1") == false);
	assert(cmp_release_version("v26.06.8-blake2b.5-modded") == false);
	assert(cmp_release_version("v26.06.8-blake2b.5-3-ge2b0374-modded") == false);
	assert(cmp_release_version("v26.06.8-blake2b") == false);

	common_shutdown();
}
